# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ci-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[linting,testing]
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src --max-line-length=127
        black --check *.py
        isort --check src/ tests/

    - name: Test with pytest
      run: |
        # do not run julia or synthea dependent tests
        pytest -m "not julia"